name: Cypress CI + Deploy Report

on:
  push:
    branches: [main]

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests and Generate HTML Report
        run: npm run test:html

      - name: Copy Report to Public Folder for GitHub Pages
        run: npm run copy:report

      - name: Upload Cypress Artifacts (Video & Mochawesome Report)
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/
            cypress/screenshots/
            cypress/reports/html/

      - name: Deploy HTML Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
