name: Cypress E2E Tests & Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm run test:report
        env:
          CI: true

      - name: Archive Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Archive Mochawesome HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: mochawesome-report
